#include "l4d_pch.h"
#include <cstdio>

// Autogenerated fallback stubs for unhooked Xbox 360 kernel/XAM/CRT imports

extern "C" void __imp__DbgBreakPoint(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ExAllocatePool(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ExAllocatePoolTypeWithTag(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ExCreateThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ExFreePool(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ExRegisterTitleTerminateNotification(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ExTerminateThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__FscGetCacheElementCount(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__FscSetCacheElementCount(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__InterlockedFlushSList(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__InterlockedPopEntrySList(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoCheckShareAccess(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoCompleteRequest(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoCreateDevice(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoDeleteDevice(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoDismountVolume(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoDismountVolumeByFileHandle(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoInvalidDeviceRequest(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoRemoveShareAccess(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__IoSetShareAccess(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeAcquireSpinLockAtRaisedIrql(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeDelayExecutionThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeEnterCriticalRegion(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeInitializeSemaphore(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeLeaveCriticalRegion(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeLockL2(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeQueryBasePriorityThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeQueryPerformanceFrequency(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeQuerySystemTime(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeRaiseIrqlToDpcLevel(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeReleaseSemaphore(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeReleaseSpinLockFromRaisedIrql(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeResetEvent(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeResumeThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeSetAffinityThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeSetBasePriorityThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeSetEvent(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeUnlockL2(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeWaitForMultipleObjects(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KeWaitForSingleObject(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KfAcquireSpinLock(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KfLowerIrql(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KfReleaseSpinLock(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__KiApcNormalRoutineNop(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__MmAllocatePhysicalMemoryEx(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__MmFreePhysicalMemory(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__MmGetPhysicalAddress(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__MmQueryAddressProtect(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__MmQueryAllocationSize(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__MmQueryStatistics(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_WSACleanup(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_WSAGetLastError(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_WSASendTo(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_WSAStartup(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetConnect(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetGetConnectStatus(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetGetTitleXnAddr(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetInAddrToXnAddr(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetQosListen(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetQosLookup(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetQosRelease(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetQosServiceLookup(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetRandom(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetServerToInAddr(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetStartup(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetUnregisterInAddr(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetXnAddrToInAddr(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_XNetXnAddrToMachineId(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll___WSAFDIsSet(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_accept(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_bind(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_closesocket(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_connect(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_getsockname(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_inet_addr(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_ioctlsocket(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_listen(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_recv(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_recvfrom(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_select(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_send(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_sendto(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_setsockopt(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NetDll_socket(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtCancelTimer(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtClearEvent(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtCreateMutant(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtCreateSemaphore(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtCreateTimer(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtDeviceIoControlFile(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtQueryFullAttributesFile(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtReleaseMutant(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtReleaseSemaphore(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtResumeThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtSetEvent(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtSetTimerEx(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtSuspendThread(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__NtWaitForMultipleObjectsEx(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ObCreateSymbolicLink(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ObDeleteSymbolicLink(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ObDereferenceObject(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ObIsTitleObject(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ObReferenceObject(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__ObReferenceObjectByHandle(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlCaptureContext(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlCompareStringN(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlFillMemoryUlong(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlFreeAnsiString(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlInitUnicodeString(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlInitializeCriticalSectionAndSpinCount(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlMultiByteToUnicodeN(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlTimeFieldsToTime(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlTimeToTimeFields(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlTryEnterCriticalSection(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlUnicodeStringToAnsiString(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlUnicodeToMultiByteN(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlUnwind(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__RtlUpcaseUnicodeChar(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__StfsControlDevice(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__StfsCreateDevice(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdCallGraphicsNotificationRoutines(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdEnableDisableClockGating(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdEnableRingBufferRPtrWriteBack(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdGetCurrentDisplayGamma(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdGetCurrentDisplayInformation(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdGetSystemCommandBuffer(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdInitializeEngines(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdInitializeRingBuffer(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdInitializeScalerCommandBuffer(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdIsHSIOTrainingSucceeded(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdPersistDisplay(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdQueryVideoFlags(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdQueryVideoMode(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdRetrainEDRAM(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdRetrainEDRAMWorker(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdSetDisplayMode(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdSetGraphicsInterruptCallback(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdSetSystemCommandBufferGpuIdentifierAddress(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdShutdownEngines(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__VdSwap(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XAudioGetSpeakerConfig(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XAudioGetVoiceCategoryVolume(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XAudioGetVoiceCategoryVolumeChangeMask(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XAudioRegisterRenderDriverClient(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XAudioSubmitRenderDriverFrame(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XAudioUnregisterRenderDriverClient(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XGetGameRegion(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XGetVideoMode(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XMACreateContext(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XMAReleaseContext(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XMsgCancelIORequest(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XMsgInProcessCall(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XMsgStartIORequest(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XMsgStartIORequestEx(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XNotifyGetNext(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamAlloc(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamContentClose(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamContentCreateEnumerator(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamContentCreateEx(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamContentFlush(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamContentGetCreator(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamContentGetDeviceData(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamCreateEnumeratorHandle(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamEnumerate(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamFree(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamGetExecutionId(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamGetPrivateEnumStructureFromHandle(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamGetSystemVersion(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamInputGetCapabilities(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamInputGetState(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamInputSetState(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamLoaderLaunchTitle(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamNotifyCreateListener(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamSessionCreateHandle(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamSessionRefObjByHandle(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamShowDeviceSelectorUI(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamShowDirtyDiscErrorUI(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamShowFriendRequestUI(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamShowFriendsUI(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamShowGameInviteUI(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamShowGamerCardUIForXUID(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamShowPlayerReviewUI(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamShowSigninUI(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamTaskCloseHandle(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamTaskSchedule(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamTaskShouldExit(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserAreUsersFriends(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserCheckPrivilege(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserCreateAchievementEnumerator(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserCreateStatsEnumerator(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserGetName(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserGetSigninInfo(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserGetSigninState(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserGetXUID(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserReadProfileSettings(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamUserWriteProfileSettings(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamVoiceClose(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamVoiceCreate(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamVoiceHeadsetPresent(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XamVoiceSubmitPacket(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XeCryptBnQwBeSigVerify(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XeCryptRotSumSha(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XeCryptSha(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XeKeysConsolePrivateKeySign(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XeKeysConsoleSignatureVerification(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XeKeysGetKey(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XexGetModuleHandle(PPCContext& ctx, uint8_t* base) {
    if (ctx.r4.u32 != 0) {
        uint32_t valBe = __builtin_bswap32(0x82000000u);
        memcpy(base + ctx.r4.u32, &valBe, 4);
    }
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XexGetModuleSection(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__XexUnloadImage(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp___snprintf(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp___snwprintf(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp___vscwprintf(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp___vsnprintf(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__sprintf(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__swprintf(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__vsprintf(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

extern "C" void __imp__vswprintf(PPCContext& ctx, uint8_t* base) {
    ctx.r3.u64 = 0;
}

