// l4d_cross_module_links.h
// Automatically generated by tools/generate_cross_module_links.py
// DO NOT EDIT MANUALLY!
#pragma once
#include <cstdint>

// Resolves all cross-module imports across all 21 Xbox 360 modules,
// populates guest memory IAT entries, and updates g_l4dGlobalDispatchTable.
void L4D_SetupCrossModuleLinks(uint8_t* guestBase);
