#include "l4d_unified_dispatch.h"
#include <iostream>
#include <fstream>
#include <vector>
#include <filesystem>
#include <cstring>

#ifdef _WIN32
#include <windows.h>
#else
#include <sys/mman.h>
#endif

// Global dispatch table instance
PPCFunc** g_l4dGlobalDispatchTable = nullptr;

// Declaration of all module mapping arrays generated by XenonRecomp
#define DECLARE_MAPPING(mod) extern PPCFuncMapping mod##_PPCFuncMappings[];

// List all 21 modules
extern PPCFuncMapping default_xex_PPCFuncMappings[];
extern PPCFuncMapping tier0_360_PPCFuncMappings[];
extern PPCFuncMapping vstdlib_360_PPCFuncMappings[];
extern PPCFuncMapping FileSystem_Stdio_360_PPCFuncMappings[];
extern PPCFuncMapping vphysics_360_PPCFuncMappings[];
extern PPCFuncMapping MaterialSystem_360_PPCFuncMappings[];
extern PPCFuncMapping shaderapidx9_360_PPCFuncMappings[];
extern PPCFuncMapping StudioRender_360_PPCFuncMappings[];
extern PPCFuncMapping datacache_360_PPCFuncMappings[];
extern PPCFuncMapping SoundEmitterSystem_360_PPCFuncMappings[];
extern PPCFuncMapping inputsystem_360_PPCFuncMappings[];
extern PPCFuncMapping launcher_360_PPCFuncMappings[];
extern PPCFuncMapping SceneFileCache_360_PPCFuncMappings[];
extern PPCFuncMapping vgui2_360_PPCFuncMappings[];
extern PPCFuncMapping vguimatsurface_360_PPCFuncMappings[];
extern PPCFuncMapping stdshader_dx9_360_PPCFuncMappings[];
extern PPCFuncMapping GameUI_360_PPCFuncMappings[];
extern PPCFuncMapping engine_360_PPCFuncMappings[];
extern PPCFuncMapping Client_360_PPCFuncMappings[];
extern PPCFuncMapping Server_360_PPCFuncMappings[];
extern PPCFuncMapping AppInstaller_360_PPCFuncMappings[];

struct ModuleMappingRegistration
{
    const char* name;
    PPCFuncMapping* mappings;
};

static ModuleMappingRegistration g_allModules[] = {
    { "default.xex", default_xex_PPCFuncMappings },
    { "tier0_360", tier0_360_PPCFuncMappings },
    { "vstdlib_360", vstdlib_360_PPCFuncMappings },
    { "FileSystem_Stdio_360", FileSystem_Stdio_360_PPCFuncMappings },
    { "vphysics_360", vphysics_360_PPCFuncMappings },
    { "MaterialSystem_360", MaterialSystem_360_PPCFuncMappings },
    { "shaderapidx9_360", shaderapidx9_360_PPCFuncMappings },
    { "StudioRender_360", StudioRender_360_PPCFuncMappings },
    { "datacache_360", datacache_360_PPCFuncMappings },
    { "SoundEmitterSystem_360", SoundEmitterSystem_360_PPCFuncMappings },
    { "inputsystem_360", inputsystem_360_PPCFuncMappings },
    { "launcher_360", launcher_360_PPCFuncMappings },
    { "SceneFileCache_360", SceneFileCache_360_PPCFuncMappings },
    { "vgui2_360", vgui2_360_PPCFuncMappings },
    { "vguimatsurface_360", vguimatsurface_360_PPCFuncMappings },
    { "stdshader_dx9_360", stdshader_dx9_360_PPCFuncMappings },
    { "GameUI_360", GameUI_360_PPCFuncMappings },
    { "engine_360", engine_360_PPCFuncMappings },
    { "Client_360", Client_360_PPCFuncMappings },
    { "Server_360", Server_360_PPCFuncMappings },
    { "AppInstaller_360", AppInstaller_360_PPCFuncMappings },
};

// Initializes the unified dispatch table and registers all module functions
void L4D_InitUnifiedDispatchTable()
{
    if (g_l4dGlobalDispatchTable != nullptr)
        return;

    size_t tableSize = L4D_TABLE_ENTRIES * sizeof(PPCFunc*);
    std::cout << "[L4D Unified Dispatch] Allocating " << (tableSize / 1024 / 1024) 
              << " MB for global function table (" << L4D_TABLE_ENTRIES << " slots)..." << std::endl;

#ifdef _WIN32
    g_l4dGlobalDispatchTable = (PPCFunc**)VirtualAlloc(nullptr, tableSize, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
#else
    g_l4dGlobalDispatchTable = (PPCFunc**)mmap(nullptr, tableSize, PROT_READ | PROT_WRITE, MAP_ANON | MAP_PRIVATE, -1, 0);
#endif

    if (!g_l4dGlobalDispatchTable) {
        std::cerr << "[L4D Unified Dispatch] FATAL: Failed to allocate global dispatch table!" << std::endl;
        std::exit(1);
    }

    size_t totalRegistered = 0;
    for (const auto& mod : g_allModules) {
        if (!mod.mappings) continue;
        size_t count = 0;
        for (size_t i = 0; mod.mappings[i].guest != 0; ++i) {
            uint32_t guest = (uint32_t)mod.mappings[i].guest;
            if (guest >= L4D_GLOBAL_BASE && (guest - L4D_GLOBAL_BASE) < L4D_GLOBAL_SPAN) {
                uint32_t idx = (guest - L4D_GLOBAL_BASE) >> 2;
                g_l4dGlobalDispatchTable[idx] = mod.mappings[i].host;
                count++;
            }
        }
        totalRegistered += count;
        std::cout << "[L4D Unified Dispatch] " << mod.name << ": registered " << count << " functions." << std::endl;
    }

    std::cout << "[L4D Unified Dispatch] Registered " << totalRegistered << " functions across 21 modules." << std::endl;
}

// Preloads PE data sections (.data, .rdata) of all 21 modules into guest memory base
bool L4D_PreloadAllPEData(uint8_t* guestBase, const std::string& peDumpsDir)
{
    std::cout << "[L4D PE Preloader] Preloading all 21 module images into guest RAM..." << std::endl;
    namespace fs = std::filesystem;

    if (!fs::exists(peDumpsDir)) {
        std::cerr << "[L4D PE Preloader] Error: PE dumps directory not found: " << peDumpsDir << std::endl;
        return false;
    }

    size_t loadedCount = 0;
    for (const auto& entry : fs::directory_iterator(peDumpsDir)) {
        if (entry.path().extension() == ".pe") {
            std::ifstream file(entry.path(), std::ios::binary);
            if (!file) continue;

            file.seekg(0, std::ios::end);
            size_t fileSize = file.tellg();
            file.seekg(0, std::ios::beg);

            std::vector<uint8_t> peData(fileSize);
            file.read((char*)peData.data(), fileSize);

            if (peData.size() < 0x200 || peData[0] != 'M' || peData[1] != 'Z')
                continue;

            uint32_t ntHeaderOffset = *(uint32_t*)&peData[0x3C];
            if (ntHeaderOffset + 0x100 > peData.size())
                continue;

            uint32_t imageBase = *(uint32_t*)&peData[ntHeaderOffset + 0x34];
            uint16_t numSections = *(uint16_t*)&peData[ntHeaderOffset + 0x06];
            uint16_t optHeaderSize = *(uint16_t*)&peData[ntHeaderOffset + 0x14];
            uint32_t sectionHeaderOffset = ntHeaderOffset + 0x18 + optHeaderSize;

            for (uint16_t s = 0; s < numSections; ++s) {
                uint32_t sOff = sectionHeaderOffset + (s * 40);
                if (sOff + 40 > peData.size()) break;

                uint32_t virtSize = *(uint32_t*)&peData[sOff + 8];
                uint32_t virtAddr = *(uint32_t*)&peData[sOff + 12];
                uint32_t rawSize = *(uint32_t*)&peData[sOff + 16];
                uint32_t rawPtr = *(uint32_t*)&peData[sOff + 20];

                // Note: These PE dumps are unpacked virtual memory images where section
                // content is laid out at virtAddr (VirtualAddress), not rawPtr.
                uint32_t srcOff = virtAddr;
                uint32_t copySize = (rawSize > 0) ? rawSize : virtSize;
                if (srcOff + copySize > peData.size()) {
                    if (srcOff < peData.size()) {
                        copySize = (uint32_t)(peData.size() - srcOff);
                    } else {
                        continue;
                    }
                }

                if (copySize > 0) {
                    uint8_t* dest = guestBase + imageBase + virtAddr;
                    memcpy(dest, &peData[srcOff], copySize);
                }
            }

            loadedCount++;
        }
    }

    std::cout << "[L4D PE Preloader] Successfully staged " << loadedCount << " module sections into guest memory." << std::endl;
    return loadedCount > 0;
}
