[main]
file_path = "../../extracted_game/root/bin/vguimatsurface_360.dll"
out_directory_path = "vguimatsurface_360"
switch_table_file_path = "vguimatsurface_360_switch_tables.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

savegprlr_14_address = 0x8492F7C0
restgprlr_14_address = 0x8492F810
